import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* todo: header 교체 */}
        <header className="border-b px-6 py-4">
          <div className="mx-auto flex max-w-5xl items-center justify-between">
            <div>
              <h1 className="text-lg font-semibold">개발자 공방</h1>
              <p className="text-sm text-gray-500">코드와 문서를 함께 만드는 공간</p>
            </div>
            <button className="rounded-md border px-4 py-2 text-sm">GitHub 로그인</button>
          </div>
        </header>
        <main className="mx-auto max-w-5xl px-6 py-10">{children}</main>
      </body>
    </html>
  );
}
