import React from 'react';
import type { Metadata } from 'next';
import { Header } from '@/shared/ui/Header';
import './globals.css';
import { QueryProvider } from '@/shared/providers/QueryProvider';
import { ModalProvider } from '@/shared/ui/modal/ModalProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <QueryProvider>
          <ModalProvider>
            <Header />
            <main className="mx-auto max-w-5xl px-6 py-10">{children}</main>
          </ModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
